### ISSUE TITLE
请问预计什么时候开源代码呢？

### ISSUE THREAD

**Issue by qinqinqaq** [zwyking/Fast-Stab#2]

**Comment by zwyking** [comment]
您好，我最近刚入职所以事情比较多，大概9月下半旬我会先开源数据集的合成算法，之后的测试代码大概要到11月了~

**Comment by qinqinqaq** [comment]
> 您好，我最近刚入职所以事情比较多，大概9月下半旬我会先开源数据集的合成算法，之后的测试代码大概要到11月了~

谢谢您的回复！  持续保持关注中...
